### ISSUE TITLE
rawsockets doesn't work with cpp backend

### ISSUE THREAD

**Issue by def-** [Araq/Nim#1460]
```nimrod
import rawsockets
```
Error:
```
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp: In function ‘addrinfo* getaddrinfo_142208(NimStringDesc*, NU16, NU8, NU8, NU8)’:
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp:579:32: error: invalid conversion from ‘const char*’ to ‘NCSTRING {aka char*}’ [-fpermissive]
   LOC6 = gai_strerror(gairesult);
                                ^
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp: In function ‘void gethostbyaddr_143246(NimStringDesc*, thostent141421*)’:
/home/deen/git/nimrod-unsorted/nimcache/stdlib_rawsockets.cpp:787:27: error: invalid conversion from ‘const char*’ to ‘NCSTRING {aka char*}’ [-fpermissive]
   LOC5 = hstrerror(h_errno);
```

**Comment by def-** [comment]
Can't reproduce anymore.

**Comment by def-** [comment]
I don't know if it actually disappeared or I just tested wrongly, but this issue is definitely back.

**Comment by def-** [comment]
This still worked until https://github.com/Araq/Nim/commit/4876aabb39bb4b488a9584684806c4b25aa04006 and got broken by https://github.com/Araq/Nim/commit/b40bfc0ce3c2b0cbfbb4a936807c7e1235bcc5f9 . But reverting that commit doesn't fix it.

**Comment by def-** [comment]
Smaller example with the same error:

```nimrod
proc fa4: array[1, bool] = discard
discard fa4()
```
```
/home/deen/git/nim-unsorted/nimcache/min.cpp: In function ‘void minInit()’:
/home/deen/git/nim-unsorted/nimcache/min.cpp:100:16: error: cannot convert ‘bool*’ to ‘bool (*)[1]’ for argument ‘1’ to ‘void fa4_90003(bool (*)[1])’
  fa4_90003(LOC1);
                ^
Error: execution of an external program failed
```

**Comment by dom96** [comment]
Interesting. Maybe we should pass a flag to the C compiler to make all warnings errors and fix all the warnings?
